### ISSUE TITLE
model with REST persistence, when calling model.save(), no params are being passed

### ISSUE THREAD

**Issue by paulbjensen** [benpickles/js-model#16]
Hi,

I'm getting a weird issue with doing model.save() on a model which has restful persistence. When I call model.save(), it is not passing any params to the restful persistence path at all. 

I've checked that attributes are set for the model, as well as the path passed to the Model.REST argument, they are both fine. Project.load() works fine in getting the collection of objects. I double-checked that there was nothing wrong with the json API being access by js-model by testing a POST request with RestClient in Ruby, and that worked fine. I'm at a loss; the problem seems to lie with js-model passing params when doing a post request.

This is on version 0.9.3 (minified) with jQuery 1.4.4 (minified).

I have a private repo where this is occurring. Let me know if you want access to it for debugging. 

Regards,

**Comment by benpickles** [comment]
Three months later I know but - did you ever get this sorted?

**Comment by paulbjensen** [comment]
Unfortunately not, I'll have another go and either close this issue or send you a copy of the source files with the error.

**Comment by benpickles** [comment]
js-model REST persistence sends data as `application/json` which rails converts to params as if it were `application/x-www-form-urlencoded`. i suspect the request body is still being seen as a JSON string (as opposed to a parsed hash/object) in which case you'll have to manually get the data out of the request.

Just a thought.

**Comment by paulbjensen** [comment]
You know what I think the issue might be? My use of .haml instead of .html.haml alongside using the inherited_resources gem. I discovered that if you have a view file named "x.haml" rather than "x.html.haml", then the controller will attempt to render the "x.haml" even if you are making a JSON request.

I'm marking this issue as closed since it's not punching me in the nuts anymore.
