### ISSUE TITLE
Next version?

### ISSUE THREAD

**Issue by ghost** [benpickles/js-model#29]
When will you release the next version?
Any future plans?

I really like the idea behind js-model and I would like to use it in my next project, but I can't use it if there is no further developement.

Especially I need to do some updates offline in localStorage and sync them with a REST api as soon as reconnected to the internet.

**Comment by benpickles** [comment]
Thanks for your kind words. I do have future plans for js-model, unfortunately I haven't set them in motion yet and it's already been quite some time since the last official release...
