### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by granteagon** [benpickles/js-model#39]
model_class_methods.js was heavily updated and removed the `all` method along with many others in b09e2dfcb18da8b5a0a81e7cb622568b5d20aa04.  It looks like now we are to rely on a functional programming method for interacting with objects of the collection.  Is that the case and can you give any details about what this move is all about?

**Comment by benpickles** [comment]
It was part of a larger refactor, restructure and rethink of the whole library but it was so long ago that I can hardly remember! Unfortunately what's on master doesn't represent a finished state as this evolution never reached a conclusion.

I'm happy to discuss further and answer any specific questions if you wish.

**Comment by granteagon** [comment]
Why did you stop working on it?  Did you find something better, or do you just not have time?  I just finished porting the code over to browserify for use in a project I am working on.

**Comment by benpickles** [comment]
I didn't have the time and things moved on - there are many well-developed alternatives.
