### ISSUE TITLE
Destroy problem when used with Rails

### ISSUE THREAD

**Issue by ghost** [benpickles/js-model#4]
Hi Ben,

Just noticed a problem when using with Rails.

Rails destroy actions return an empty string by default meaning the 'ajaxError' event gets triggered. This may well happen with updates too but I've not tested.

I'm not sure of the best way round this as there is already a ticket for Rails which they're not going to fix: https://rails.lighthouseapp.com/projects/8994/tickets/5199-respond_with-returns-on-put-and-delete-verb

What are your thoughts on this?

Cheers,

Jamie

**Comment by benpickles** [comment]
What version of js-model are you using? A guard for that issue has been there since v0.8.2:

http://github.com/benpickles/js-model/commit/1d9d72acd6c1db2f7ddbd1e76e496025593d023f

**Comment by ghost** [comment]
I'm using 0.8.4. The only way I found to get around it was to force the response given by the destroy action to be an empty JSON object:

```
    respond_to do |format|
      format.json { render :text => '{}', :status => :ok }
    end
```

**Comment by ghost** [comment]
Sorry, I should probably mention that I am using Rails 3 and the problem comes when using respond_with.

**Comment by benpickles** [comment]
OK I'll check it out.

**Comment by benpickles** [comment]
I've tried it with a fresh Rails 3.0.0.rc app and js-model 0.8.4 and it works fine for me.

**Comment by ghost** [comment]
If that's with the default generated scaffold it's probably fine, it's in conjunction with respond_with that things get tricky. You may not be seeing the error as it fails silently, you will need something like the following:

```
$('#status').ajaxError(function() {
  alert('Problem communicating with server.');
})
```

**Comment by benpickles** [comment]
Hi Jamie,

the issue wasn't showing up in my tests because my JSON wasn't being served as "application/json" and therefore wasn't being automatically parsed by jQuery. I've pushed an update to fix this:

http://github.com/benpickles/js-model/commit/d96f47e5193f8de2cb7ba68349aaf1a08b9beeb4

Ben

**Comment by ghost** [comment]
Excellent, that's great. I see that you've fixed for updates too.
