### ISSUE TITLE
Runtime VERSION constant

### ISSUE THREAD

**Issue by ghost** [benpickles/js-model#5]
...would be useful. In the case of embedding widgets in other sites where this library could potentially be loaded already it would be nice if version could be detected. It's a good practice for potentially common libraries. In jQuery and Underscore there's also a noConflict() method, but knowing the version would at least make it possible to detect if versions match. Usually VERSION constant within the namespace is a practice: Model.VERSION. What u say? :)

**Comment by benpickles** [comment]
It would absolutely be useful! I'm working on a new bundling script (in a unpushed branch) and have now added Model.VERSION, it will appear in the next release.

Thanks for posting, Ben
